### ISSUE TITLE
Missing Staging File

### ISSUE THREAD

**Issue by a-mayeli** [NirLab-TAU/sleepeegpy#2]
Could you please upload the file name staging.txt that is been used in the demo? I couldn't find it anywhere on zenodo nor here. Thanks!

**Comment by Genuster** [comment]
Sure! I'll put it here in the meantime.
[staging.txt](https://github.com/NirLab-TAU/sleepeegpy/files/13758338/staging.txt)

**Comment by yardenmezi** [comment]
The file is now available in Zenodo
https://zenodo.org/records/13903088
